version: '3'
services:
  app:
    build: .
    volumes:
      - .:/esprit
      - /esprit/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: esprit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
volumes:
  db_data:
    driver: local
