FROM node:10

RUN apt-get update && \
    apt-get -y install git unzip build-essential autoconf libtool
RUN git clone https://github.com/google/protobuf.git && \
    cd protobuf && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install && \
    ldconfig && \
    make clean && \
    cd .. && \
    rm -r protobuf

RUN mkdir /esprit

ENV APP_ROOT /esprit
WORKDIR $APP_ROOT

RUN npm i

EXPOSE 3000
