version: '3'
services:
  app:
    build: .
    volumes:
      - .:/esprit
    ports:
      - "3000:3000"
    command: echo 1
    links:
      - db
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: esprit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
