version: '3'
services:
  db:
    build: ./dynamodb
    volumes:
      - db_data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
  app:
    build: .
    volumes:
      - .:/esprit
    ports:
      - "3000:3000"
    command: sls offline --host 0.0.0.0 --useChildProcesses --noPrependStageInUrl
    depends_on:
      - db
volumes:
  db_data:
    driver: local
