openapi: 3.0.0
info:
  title: 'esprit API'
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
    description: local mock server
paths:
  /signin:
    post:
      summary: Signin
      operationId: signin
      description: |-
        サインイン
      requestBody:
        description: Signin parameter
        required: true
        content:
          application/json:
            schema:
              $ref: './requests/signin_param.yaml'
      responses:
        '200':
          description: user credential response
          content:
            application/json:
              schema:
                $ref: './response/user_credential_response.yaml'
  /users:
    post:
      summary: Create User
      operationId: postUser
      description: |-
        ユーザーの新規作成
      requestBody:
        description: Create user parameter
        required: true
        content:
          application/json:
            schema:
              $ref: './requests/create_user_params.yaml'
      responses:
        '200':
          description: user credential response
          content:
            application/json:
              schema:
                $ref: './response/user_credential_response.yaml'
  /users/me:
    get:
      summary: Get Me
      operationId: getMe
      security:
        - bearerAuth: []
      description: |-
        自分のユーザー情報を取得する
      responses:
        '200':
          description: User response
          content:
            application/json:
              schema:
                $ref: './response/user_response.yaml'
    patch:
      summary: Patch Me
      operationId: patchMe
      security:
        - bearerAuth: []
      description: |-
        自分のユーザー情報を更新する
      requestBody:
        description: Update user parameter
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: './requests/update_user_params.yaml'
      responses:
        '200':
          description: User response
          content:
            application/json:
              schema:
                $ref: './response/user_response.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
