openapi: 3.0.0
info:
  title: 'esprit API'
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
    description: local mock server
paths:
  /users:
    get:
      summary: users
      description: |-
        users
      responses:
        '200':
          description: users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: taro
                  required:
                    - id
                    - name
